### ISSUE TITLE
Bug: Opacity Issue

### ISSUE THREAD

**Issue by usernotnull** [shoedler/crossbow#27]
**Describe the bug**
The source file name was a great addition to the results list! The issue is it's hard to read with the color/opacity set in both light and dark themes.
To confirm, I reverted from my custom dark theme to the default theme and tried both light and dark versions, showing the same issue as the screenshots below.

Also notice that in light mode, the "Heading" is even more affected (I'm a dark mode guy but better be thorough 😄).

**Screenshots**
<img width="266" alt="image" src="https://github.com/shoedler/crossbow/assets/15612814/c86cafba-c49c-4ca6-9e6e-e013b66d6d85">

<img width="263" alt="image" src="https://github.com/shoedler/crossbow/assets/15612814/6836150d-4f5c-48c6-86bb-048a5426f552">

**Comment by shoedler** [comment]
Thanks for pointing this out!
Could you try it with the attached insider build? I only adjusted the css stylesheet (Removed the opacities)
Since I'm using CSS variables for colors and opacities provided by obsidian. I'm interested to see if perhaps your custom theme is wrong or maybe my combination of colors and opacities are unfortunate.
[crossbow-1.3.0.insider.zip](https://github.com/shoedler/crossbow/files/11618553/crossbow-1.3.0.insider.zip)

**Comment by usernotnull** [comment]
@shoedler The build you uploaded doesn't show changes in opacity, here is a devtools screenshot even highlighting the contrast issue:

<img width="301" alt="image" src="https://github.com/shoedler/crossbow/assets/15612814/06a40ecd-8ec2-4d16-ab03-ca7a19756434">

Here is the default obsidian theme too with same issue (slightly better but still not enough in terms of contrast accessibility):

<img width="288" alt="image" src="https://github.com/shoedler/crossbow/assets/15612814/750e58aa-b042-401b-bb5d-1197257ac3e0">

**Comment by usernotnull** [comment]
Tinkering around the changes, it's slightly better when you commented out "opacity: var(--icon-opacity);" 
What made it work was when I changed color: var(--color-base-40); to color: var(--color-base-60);
