### ISSUE TITLE
Performance - incompatible with very large files

### ISSUE THREAD

**Issue by kraibse** [shoedler/crossbow#3]
Crossbow works well with smaller files but gets really heavy on large documents. I am talking about my specific example of a document of 29205 words.

**What happens?**
Obsidian freezes but does not crash. Whenever I switch a file by clicking on an open pane, I can unlock Obsidian after waiting a little while.
It does also not matter if the Crossbow pane is active or not.

**What could be done?**
Crossbow could load and analyze a set amount of words around the cursor position so it doesn't slow down ad infinitum.
It could also deactivate when the pane is not active.

**Comment by shoedler** [comment]
Hi @kraibse 
I've just released [a new version](https://github.com/shoedler/crossbow/releases/tag/1.2.0) of the plugin. I've tested it with some very large notes (>50k words and 350k chars) and it seems to run smoothly.

I've also implemented your suggestion where crossbow will not run in the background if you close the crossbow view.
Let me know if this fixes your issues. If so, please close this issue

**Comment by kraibse** [comment]
Hello again
thanks for putting attention to this issue! I've just tested the latest version with the aforementioned file.

From what I can see the performance has much improved to the previous version. Before I didn't even have the chance to edit the large document, now I do, though. Performance also increases drastically when the crossbow pane is not active!

That said, having Crossbow seems to be refreshing when scrolling through the document and therefore still handles very choppily. I'll open another issue for additional ideas and feature requests.

**Comment by shoedler** [comment]
It doesn't update the suggestions when you're just scrolling
You can confim this by turning on the debug logs in the crossbow settings. Then, open the dev tools (Ctrl+Shift+I) and clear the output (See where the cursor is in the following screenshot).
Crossbow will log two entries to the console if the suggestions get updated (See screenshot). So, if you're just scrolling, no additional logs by crossbow should be made.
![image](https://user-images.githubusercontent.com/38029550/234707667-a2f7d44b-f427-4a6f-a277-3ca8b8687f4a.png)
I'm guessing something else is eating up your performance. Please get back to me if you've tested this

**Comment by kraibse** [comment]
Finally, I've gotten to testing this plugin without any other plugins installed / activated. I was hoping some other plugin was the cause for the scroll lag but nevertheless crossbow seems to be the culprit.

It's like going from 60fps to <=10fps when scrolling with the crossbow pane enabled.

**Comment by shoedler** [comment]
Alright, I see the problem now. The issue seems to be the amount of suggestions - probably overloading the DOM.
I'm still interested to know if somehow crossbow gets triggered in your scenario (https://github.com/shoedler/crossbow/issues/3#issuecomment-1524074202).
I'll have to think about it - I'm probably not getting around stemming the suggestions first (Normalizing them). Which would include removing any punctuation like we see in your screenshot and therefore reduce the amount of suggestions made.
I was initially leaning away from this approach because it'll constrain crossbow to languages.
I'll get back if to you if I have any updates

**Comment by shoedler** [comment]
I've just released [1.2.1](https://github.com/shoedler/crossbow/releases/tag/1.2.1), this should be fixed. 
Please confirm and close this issue. If you still encounter the same bug, notify me on this channel.

**Comment by kraibse** [comment]
I've had time to check it out today and this is what I've found:

- Normalized tokens result in a better and cleaner experience. Thank you!

- Issue of lagging still persists when scrolling through the large file with the crossbow pane loading suggestions of the same file
- Issue of lagging does not persist when working in the large file while loading suggestions on another file (in this case smaller)

New settings applied:
- disabled auto refresh

Soon, I'll be taking a look through the code to see if I find anything of interest. Until then, how would I best proceed debugging issues with your plugin?

**Comment by shoedler** [comment]
Thanks again for your feedback!
My suspicion still is the amount of suggestions - maybe lazy loading the nested tree items didn't yield the expected performance gains (It did in my case tough).

Currently, the amount of suggestions generated is not being logged to console.
You can, however do this manually:

1. Open the dev tools (Ctrl+Shift+I)
2. Use the item selector (Ctrl+Shift+C) on the crossbow view - move the cursor to where you see `div.view-content` in the tooltip:
![image](https://github.com/shoedler/crossbow/assets/38029550/d6549794-68a3-4033-a990-7c5dfa7b2e30)
3. Select the nested `div` with the `cb-view-tree` class, right click, "Copy", "Copy JS path":
![image](https://github.com/shoedler/crossbow/assets/38029550/cc83dfe8-1239-4dc1-9a9a-c620a92137c4)
4. Switch to the console tab and paste (Ctrl+V)
5. Append ".children.length" and hit Enter

This should return a number, in this example, I got 30 suggestions:
![image](https://github.com/shoedler/crossbow/assets/38029550/3a0c0202-496c-403b-b994-d575bd7b1703)

Run this procedure on your large file and get back to me with your result.

**Comment by kraibse** [comment]
Great! I went through that procedure and can proudly present my result to you!

Document statistics:
- 32376 words
- 219472 characters
- 839 suggestions

![grafik](https://github.com/shoedler/crossbow/assets/33869366/b9bbc0e2-676f-4828-923b-fd4dc77d5c85)

Maybe, at some point, you'd have to consider semantic similarity and a service that checks for that in the cache. I'm sure this would be a performance killer though.

**Comment by shoedler** [comment]
Alright! 839 seems reasonable tough. I've tried to reproduce this on my hardware in my gigantic testfile I mentioned earlier (>50k words and 350k chars) which - since I just copy / pasted some content - only yielded 82 suggestions. 
But they have large occurrence counts (Some over 800) which, when clicked on, generate over 800 tree items which I'm easily able to scroll trough fluidly and continue using obsidian without any hiccups. 

I'm running on a pretty potent laptop tough (i7-13700H + 32GB). I can't imagine that other hardware would be that much slower, as it runs nicely with over 2000 tree items rendered in the DOM. (Using some 450MB of RAM tough).

Could you tell me what hardware you're running on?

About your suggestion on looking for semantic similarity - your right, it'd definitely result in less suggestion. But I don't really want to add such a feature, as I want to keep this plugin useful for multiple languages. Stemming words for multiple languages correctly is a gigantic task which I just don't have the time to implement.

**Comment by kraibse** [comment]
So far, I have only been able to test it on my mobile setup (which is overall not a bad setup):

- i5-8350U running at apprx. 3.5 GHz (base 1.7GHz)
- 32 GB RAM

I will, as soon as I get to it, test it out on my desktop too.

**Comment by shoedler** [comment]
Seems decent at the very least! I was kinda hoping you'd be running on very slow hardware - then I could've just added a minimum systems requirement spec 🤣.

I have to think about this some more. In the mean time, could you retry the newest [Release 1.3.0](https://github.com/shoedler/crossbow/releases/tag/1.3.0)? As I mentioned in https://github.com/shoedler/crossbow/issues/17#issuecomment-1556031039, this release contains some pretty potent performance optimizations.

**Comment by kraibse** [comment]
The 1.3.0 release fixed the performance issues I had with the plugin. Now, it works flawlessly after the initial scan. At this point I would consider this issue solved.

**Comment by shoedler** [comment]
Very satisfying to hear this! Thanks for being on top of it!

**Comment by kraibse** [comment]
@shoedler 
If the need ever arises to bump up the performance even more, you could take a look at the trie data structure. It is a method enabling faster string queries by building a tree of the possible solutions.

https://www.npmjs.com/package/trie-search#performance

I stumbled upon this data structure in this video: https://youtu.be/Fs4sMaltizk
