### ISSUE TITLE
Plugin Settings: Toggle for Enabling/Disabling, Custom Refresh Cycle, and Manual Reload Button

### ISSUE THREAD

**Issue by kraibse** [shoedler/crossbow#4]
Hello again,

I have a few ideas regarding useful settings for the plugin.

- Toggle for enabling/disabling the plugin
- A setting to set a custom refresh cycle (like with dataview)
- Toggle for enabling/disabling automatic refreshing

The last option then implies a new manual method (like a button in the crossbow view) for reloading the suggestions in the window.

Thanks for the consideration!

**Comment by shoedler** [comment]
Hi again
Thanks for your suggestions! I'll address them one by one:
> - Toggle for enabling/disabling the plugin
Obsidian already has a solution for this. Checkout the "Community Plugins" entry in the options. You can enable / disable the plugin from there.
> - A setting to set a custom refresh cycle (like with dataview)
This is a good idea. It's going to be more of a custom "delay" tough. Since the refresh is triggered when Obsidian updates the cache for the note you're editing (Takes about 2.5s after you finished typing). So it's be a slider say from 2.5s to 20s.
> - Toggle for enabling/disabling automatic refreshing
Also a good idea, and easy enough to add.

I'll get back to you once I get around to adding this stuff

**Comment by shoedler** [comment]
Will be in the next release

**Comment by shoedler** [comment]
It's now live: https://github.com/shoedler/crossbow/releases/tag/1.2.1

**Comment by kraibse** [comment]
This looks great so far. I like the new feel of the settings window.

Regarding the manual refresh I have these few suggestions:

- Could you add the manual refresh button to the crossbow pane even when automatic reloading is enabled?
- Could you add a button label saying "Refresh" to make interaction more intuitive?
